USE master;
GO

-- Giải phóng kết nối và xóa DB cũ
IF DB_ID(N'Giay') IS NOT NULL
BEGIN
    ALTER DATABASE Giay SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE Giay;
END;
GO

CREATE DATABASE Giay;
GO
USE Giay;
GO

SET NOCOUNT ON;
GO

-------------------------------------------------------
-- 1. NHÓM BẢNG QUẢN TRỊ & KHÁCH HÀNG
-------------------------------------------------------
CREATE TABLE Role (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Role PRIMARY KEY DEFAULT NEWID(),
    Ten VARCHAR(50) NOT NULL CONSTRAINT UQ_Role_Ten UNIQUE,
    MoTa NVARCHAR(200) NULL
);

CREATE TABLE NhanVien (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_NhanVien PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(20) NOT NULL CONSTRAINT UQ_NhanVien_Ma UNIQUE,
    TenDangNhap VARCHAR(50) NOT NULL CONSTRAINT UQ_NhanVien_TenDangNhap UNIQUE,
    HoTen NVARCHAR(100) NOT NULL,
    Email VARCHAR(100) NULL CONSTRAINT UQ_NhanVien_Email UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    Sdt VARCHAR(20) NULL,
    DiaChi NVARCHAR(200) NULL,
    RoleId UNIQUEIDENTIFIER NOT NULL,
    TrangThai INT NOT NULL DEFAULT 1,
    NgayTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    NgayCapNhat DATETIME2 NULL,
    CONSTRAINT FK_NhanVien_Role FOREIGN KEY (RoleId) REFERENCES Role(Id)
);

CREATE TABLE KhachHang (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_KhachHang PRIMARY KEY DEFAULT NEWID(),
    TenDangNhap VARCHAR(50) NOT NULL CONSTRAINT UQ_KhachHang_TenDangNhap UNIQUE,
    HoTen NVARCHAR(100) NOT NULL,
    Email VARCHAR(100) NULL CONSTRAINT UQ_KhachHang_Email UNIQUE,
    Sdt VARCHAR(20) NULL,
    DiaChi NVARCHAR(200) NULL,
    NgaySinh DATE NULL,
    MatKhau VARCHAR(255) NOT NULL,
    TrangThai INT NOT NULL DEFAULT 1,
    NgayTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    NgayCapNhat DATETIME2 NULL
);

-------------------------------------------------------
-- 2. NHÓM BẢNG DANH MỤC SẢN PHẨM
-------------------------------------------------------
CREATE TABLE ThuongHieu (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Ten NVARCHAR(200) NOT NULL UNIQUE,
    MoTa NVARCHAR(500) NULL,
    TrangThai INT NOT NULL DEFAULT 1
);

CREATE TABLE LoaiGiay (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Ten NVARCHAR(100) NOT NULL UNIQUE,
    MoTa NVARCHAR(500) NULL,
    TrangThai INT NOT NULL DEFAULT 1
);

CREATE TABLE ChatLieu (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Ten NVARCHAR(100) NOT NULL UNIQUE,
    MoTa NVARCHAR(500) NULL,
    TrangThai INT NOT NULL DEFAULT 1
);

CREATE TABLE DotGiamGia (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Ma NVARCHAR(100) NOT NULL UNIQUE,
    Ten NVARCHAR(200) NOT NULL,
    PhanTram DECIMAL(5,2) NULL,
    NgayBatDau DATETIME2 NULL,
    NgayKetThuc DATETIME2 NULL,
    KichHoat BIT NOT NULL DEFAULT 1
);

-------------------------------------------------------
-- 3. NHÓM BẢNG SẢN PHẨM CHÍNH
-------------------------------------------------------
CREATE TABLE Giay (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Ma NVARCHAR(100) NOT NULL UNIQUE,
    Ten NVARCHAR(300) NOT NULL,
    ThuongHieuId INT NOT NULL,
    LoaiGiayId INT NOT NULL,
    ChatLieuId INT NOT NULL,
    GioiTinh INT NULL,
    DotGiamGiaId INT NULL,
    TrangThai INT NOT NULL DEFAULT 1,
    NgayTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CONSTRAINT FK_Giay_ThuongHieu FOREIGN KEY (ThuongHieuId) REFERENCES ThuongHieu(Id),
    CONSTRAINT FK_Giay_LoaiGiay FOREIGN KEY (LoaiGiayId) REFERENCES LoaiGiay(Id),
    CONSTRAINT FK_Giay_ChatLieu FOREIGN KEY (ChatLieuId) REFERENCES ChatLieu(Id),
    CONSTRAINT FK_Giay_DotGiamGia FOREIGN KEY (DotGiamGiaId) REFERENCES DotGiamGia(Id)
);

CREATE TABLE GiayChiTiet (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    GiayId INT NOT NULL,
    MaBienThe NVARCHAR(150) NOT NULL UNIQUE,
    MauSac VARCHAR(50)  NOT NULL,
    KichCo VARCHAR(50) NOT NULL,
    SoLuong INT NOT NULL DEFAULT 0,
    GiaGoc DECIMAL(18,2) NOT NULL,
    GiaBan DECIMAL(18,2) NOT NULL,
    SKU NVARCHAR(150) NOT NULL UNIQUE,
   CONSTRAINT FK_GiayChiTiet_Giay FOREIGN KEY (GiayId) REFERENCES Giay(Id) ON DELETE CASCADE
);

-- (Các bảng PhieuGiamGia, HoaDon, ThanhToan... tiếp tục như code của bạn)
-- Đã lược bớt các ràng buộc CHECK phức tạp để giảm tải bộ nhớ khi khởi tạo

CREATE TABLE HinhAnhGiay (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_HinhAnhGiay PRIMARY KEY,
    GiayChiTietId INT NOT NULL,
    LoaiHinh INT NOT NULL,
    Url NVARCHAR(1000) NOT NULL,
    MoTa NVARCHAR(300) NULL,
    LaHinhChinh BIT NOT NULL CONSTRAINT DF_HinhAnhGiay_LaHinhChinh DEFAULT 0,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_HinhAnhGiay_NgayTao DEFAULT SYSDATETIME(),
    NgayCapNhat DATETIME2 NULL,
    CONSTRAINT CK_HinhAnhGiay_Loai CHECK (LoaiHinh IN (1, 2, 3)),
    CONSTRAINT FK_HinhAnhGiay_GiayChiTiet FOREIGN KEY (GiayChiTietId) REFERENCES GiayChiTiet(Id) ON DELETE CASCADE
);
GO

CREATE TABLE PhieuGiamGia (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PhieuGiamGia PRIMARY KEY,
    Ma NVARCHAR(100) NOT NULL,
    Ten NVARCHAR(200) NOT NULL,
    Loai INT NOT NULL,
    GiaTri DECIMAL(18,2) NOT NULL,
    NgayBatDau DATETIME2 NULL,
    NgayKetThuc DATETIME2 NULL,
    SoLuong INT NOT NULL,
    KichHoat BIT NOT NULL CONSTRAINT DF_PhieuGiamGia_KichHoat DEFAULT 1,
    TrangThai INT NOT NULL CONSTRAINT DF_PhieuGiamGia_TrangThai DEFAULT 1,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_PhieuGiamGia_NgayTao DEFAULT SYSDATETIME(),
    NgayCapNhat DATETIME2 NULL,
    CONSTRAINT UQ_PhieuGiamGia_Ma UNIQUE (Ma),
    CONSTRAINT CK_PhieuGiamGia_Loai CHECK (Loai IN (1, 2, 3)),
    CONSTRAINT CK_PhieuGiamGia_GiaTri CHECK (GiaTri >= 0),
    CONSTRAINT CK_PhieuGiamGia_SoLuong CHECK (SoLuong >= 0),
    CONSTRAINT CK_PhieuGiamGia_TrangThai CHECK (TrangThai IN (0, 1)),
    CONSTRAINT CK_PhieuGiamGia_ThoiGian CHECK (NgayKetThuc IS NULL OR NgayBatDau IS NULL OR NgayKetThuc >= NgayBatDau)
);
GO

CREATE TABLE PhieuGiamGiaKH (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PhieuGiamGiaKH PRIMARY KEY,
    PhieuGiamGiaId INT NOT NULL,
    KhachHangId UNIQUEIDENTIFIER NOT NULL,
    DaSuDung BIT NOT NULL CONSTRAINT DF_PhieuGiamGiaKH_DaSuDung DEFAULT 0,
    NgaySuDung DATETIME2 NULL,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_PhieuGiamGiaKH_NgayTao DEFAULT SYSDATETIME(),
    CONSTRAINT UQ_PhieuGiamGiaKH UNIQUE (PhieuGiamGiaId, KhachHangId),
    CONSTRAINT FK_PhieuGiamGiaKH_PhieuGiamGia FOREIGN KEY (PhieuGiamGiaId) REFERENCES PhieuGiamGia(Id) ON DELETE CASCADE,
    CONSTRAINT FK_PhieuGiamGiaKH_KhachHang FOREIGN KEY (KhachHangId) REFERENCES KhachHang(Id) ON DELETE CASCADE
);
GO

CREATE TABLE GioHang (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_GioHang PRIMARY KEY,
    KhachHangId UNIQUEIDENTIFIER NOT NULL,
    KichHoat BIT NOT NULL CONSTRAINT DF_GioHang_KichHoat DEFAULT 1,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_GioHang_NgayTao DEFAULT SYSDATETIME(),
    NgayCapNhat DATETIME2 NULL,
    CONSTRAINT UQ_GioHang_KhachHang UNIQUE (KhachHangId),
    CONSTRAINT FK_GioHang_KhachHang FOREIGN KEY (KhachHangId) REFERENCES KhachHang(Id) ON DELETE CASCADE
);
GO

CREATE TABLE GioHangChiTiet (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_GioHangChiTiet PRIMARY KEY,
    GioHangId INT NOT NULL,
    GiayChiTietId INT NOT NULL,
    SoLuong INT NOT NULL CONSTRAINT DF_GioHangChiTiet_SoLuong DEFAULT 1,
    GiaTaiThoiDiem DECIMAL(18,2) NOT NULL,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_GioHangChiTiet_NgayTao DEFAULT SYSDATETIME(),
    NgayCapNhat DATETIME2 NULL,
    CONSTRAINT UQ_GioHangChiTiet UNIQUE (GioHangId, GiayChiTietId),
    CONSTRAINT CK_GioHangChiTiet_SoLuong CHECK (SoLuong > 0),
    CONSTRAINT CK_GioHangChiTiet_Gia CHECK (GiaTaiThoiDiem >= 0),
    CONSTRAINT FK_GioHangChiTiet_GioHang FOREIGN KEY (GioHangId) REFERENCES GioHang(Id) ON DELETE CASCADE,
    CONSTRAINT FK_GioHangChiTiet_GiayChiTiet FOREIGN KEY (GiayChiTietId) REFERENCES GiayChiTiet(Id)
);
GO

CREATE TABLE HoaDon (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_HoaDon PRIMARY KEY,
    Ma NVARCHAR(150) NOT NULL,
    KhachHangId UNIQUEIDENTIFIER NOT NULL,
    NhanVienId UNIQUEIDENTIFIER NULL,
    PhieuGiamGiaId INT NULL,
    NgayLap DATETIME2 NOT NULL CONSTRAINT DF_HoaDon_NgayLap DEFAULT SYSDATETIME(),
    NgayThanhToan DATETIME2 NULL,
    TrangThai INT NOT NULL,
    TongTien DECIMAL(18,2) NOT NULL,
    GhiChu NVARCHAR(1000) NULL,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_HoaDon_NgayTao DEFAULT SYSDATETIME(),
    NgayCapNhat DATETIME2 NULL,
    CONSTRAINT UQ_HoaDon_Ma UNIQUE (Ma),
    CONSTRAINT CK_HoaDon_TrangThai CHECK (TrangThai IN (1, 2, 3, 4)),
    CONSTRAINT CK_HoaDon_TongTien CHECK (TongTien >= 0),
    CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY (KhachHangId) REFERENCES KhachHang(Id),
    CONSTRAINT FK_HoaDon_NhanVien FOREIGN KEY (NhanVienId) REFERENCES NhanVien(Id),
    CONSTRAINT FK_HoaDon_PhieuGiamGia FOREIGN KEY (PhieuGiamGiaId) REFERENCES PhieuGiamGia(Id)
);
GO

CREATE TABLE HoaDonChiTiet (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_HoaDonChiTiet PRIMARY KEY,
    HoaDonId INT NOT NULL,
    GiayChiTietId INT NOT NULL,
    SoLuong INT NOT NULL CONSTRAINT DF_HoaDonChiTiet_SoLuong DEFAULT 1,
    GiaDonVi DECIMAL(18,2) NOT NULL,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_HoaDonChiTiet_NgayTao DEFAULT SYSDATETIME(),
    CONSTRAINT UQ_HoaDonChiTiet UNIQUE (HoaDonId, GiayChiTietId),
    CONSTRAINT CK_HoaDonChiTiet_SoLuong CHECK (SoLuong > 0),
    CONSTRAINT CK_HoaDonChiTiet_Gia CHECK (GiaDonVi >= 0),
    CONSTRAINT FK_HoaDonChiTiet_HoaDon FOREIGN KEY (HoaDonId) REFERENCES HoaDon(Id) ON DELETE CASCADE,
    CONSTRAINT FK_HoaDonChiTiet_GiayChiTiet FOREIGN KEY (GiayChiTietId) REFERENCES GiayChiTiet(Id)
);
GO

CREATE TABLE DanhGia (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DanhGia PRIMARY KEY,
    KhachHangId UNIQUEIDENTIFIER NOT NULL,
    GiayId INT NOT NULL,
    HoaDonId INT NULL,
    SoSao INT NOT NULL,
    NoiDung NVARCHAR(1000) NULL,
    TrangThai INT NOT NULL CONSTRAINT DF_DanhGia_TrangThai DEFAULT 1,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_DanhGia_NgayTao DEFAULT SYSDATETIME(),
    NgayCapNhat DATETIME2 NULL,
    CONSTRAINT UQ_DanhGia_KhachHang_Giay UNIQUE (KhachHangId, GiayId),
    CONSTRAINT CK_DanhGia_SoSao CHECK (SoSao BETWEEN 1 AND 5),
    CONSTRAINT CK_DanhGia_TrangThai CHECK (TrangThai IN (0, 1)),
    CONSTRAINT FK_DanhGia_KhachHang FOREIGN KEY (KhachHangId) REFERENCES KhachHang(Id),
    CONSTRAINT FK_DanhGia_Giay FOREIGN KEY (GiayId) REFERENCES Giay(Id),
    CONSTRAINT FK_DanhGia_HoaDon FOREIGN KEY (HoaDonId) REFERENCES HoaDon(Id)
);
GO

CREATE TABLE ThanhToan (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ThanhToan PRIMARY KEY,
    HoaDonId INT NOT NULL,
    MaGiaoDich NVARCHAR(200) NULL,
    HinhThuc INT NOT NULL,
    SoTien DECIMAL(18,2) NOT NULL,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_ThanhToan_NgayTao DEFAULT SYSDATETIME(),
    TrangThai INT NOT NULL,
    CONSTRAINT CK_ThanhToan_HinhThuc CHECK (HinhThuc IN (1, 2, 3)),
    CONSTRAINT CK_ThanhToan_TrangThai CHECK (TrangThai IN (0, 1, 2)),
    CONSTRAINT CK_ThanhToan_SoTien CHECK (SoTien >= 0),
    CONSTRAINT FK_ThanhToan_HoaDon FOREIGN KEY (HoaDonId) REFERENCES HoaDon(Id) ON DELETE CASCADE
);
GO

CREATE TABLE PhieuTraHang (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PhieuTraHang PRIMARY KEY,
    Ma NVARCHAR(150) NOT NULL,
    HoaDonId INT NOT NULL,
    KhachHangId UNIQUEIDENTIFIER NOT NULL,
    NhanVienId UNIQUEIDENTIFIER NULL,
    LyDo NVARCHAR(500) NULL,
    TongTienHoan DECIMAL(18,2) NOT NULL,
    HinhThucHoan INT NOT NULL,
    TrangThai INT NOT NULL CONSTRAINT DF_PhieuTraHang_TrangThai DEFAULT 1,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_PhieuTraHang_NgayTao DEFAULT SYSDATETIME(),
    NgayCapNhat DATETIME2 NULL,
    CONSTRAINT UQ_PhieuTraHang_Ma UNIQUE (Ma),
    CONSTRAINT CK_PhieuTraHang_HinhThucHoan CHECK (HinhThucHoan IN (1, 2, 3)),
    CONSTRAINT CK_PhieuTraHang_TrangThai CHECK (TrangThai IN (1, 2, 3)),
    CONSTRAINT CK_PhieuTraHang_TongTienHoan CHECK (TongTienHoan >= 0),
    CONSTRAINT FK_PhieuTraHang_HoaDon FOREIGN KEY (HoaDonId) REFERENCES HoaDon(Id),
    CONSTRAINT FK_PhieuTraHang_KhachHang FOREIGN KEY (KhachHangId) REFERENCES KhachHang(Id),
    CONSTRAINT FK_PhieuTraHang_NhanVien FOREIGN KEY (NhanVienId) REFERENCES NhanVien(Id)
);
GO

CREATE TABLE PhieuTraHangChiTiet (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PhieuTraHangChiTiet PRIMARY KEY,
    PhieuTraHangId INT NOT NULL,
    HoaDonChiTietId INT NULL,
    GiayChiTietId INT NOT NULL,
    SoLuongTra INT NOT NULL CONSTRAINT DF_PhieuTraHangChiTiet_SoLuongTra DEFAULT 1,
    GiaBan DECIMAL(18,2) NOT NULL,
    ThanhTien DECIMAL(18,2) NOT NULL,
    GhiChu NVARCHAR(500) NULL,
    NgayTao DATETIME2 NOT NULL CONSTRAINT DF_PhieuTraHangChiTiet_NgayTao DEFAULT SYSDATETIME(),
    CONSTRAINT CK_PhieuTraHangChiTiet_SoLuongTra CHECK (SoLuongTra > 0),
    CONSTRAINT CK_PhieuTraHangChiTiet_GiaBan CHECK (GiaBan >= 0),
    CONSTRAINT CK_PhieuTraHangChiTiet_ThanhTien CHECK (ThanhTien >= 0),
    CONSTRAINT FK_PhieuTraHangChiTiet_PhieuTraHang FOREIGN KEY (PhieuTraHangId) REFERENCES PhieuTraHang(Id) ON DELETE CASCADE,
    CONSTRAINT FK_PhieuTraHangChiTiet_HoaDonChiTiet FOREIGN KEY (HoaDonChiTietId) REFERENCES HoaDonChiTiet(Id),
    CONSTRAINT FK_PhieuTraHangChiTiet_GiayChiTiet FOREIGN KEY (GiayChiTietId) REFERENCES GiayChiTiet(Id)
);
GO

CREATE INDEX IX_NhanVien_RoleId ON NhanVien(RoleId);
CREATE INDEX IX_Giay_DotGiamGiaId ON Giay(DotGiamGiaId);
CREATE INDEX IX_GiayChiTiet_GiayId ON GiayChiTiet(GiayId);
CREATE INDEX IX_GiayChiTiet_MauSac ON GiayChiTiet(MauSac);
CREATE INDEX IX_GiayChiTiet_KichCo ON GiayChiTiet(KichCo);
CREATE INDEX IX_GioHangChiTiet_GioHangId ON GioHangChiTiet(GioHangId);
CREATE INDEX IX_HoaDon_KhachHangId ON HoaDon(KhachHangId);
CREATE INDEX IX_HoaDon_NhanVienId ON HoaDon(NhanVienId);
CREATE INDEX IX_HoaDon_PhieuGiamGiaId ON HoaDon(PhieuGiamGiaId);
CREATE INDEX IX_HoaDonChiTiet_HoaDonId ON HoaDonChiTiet(HoaDonId);
CREATE INDEX IX_DanhGia_GiayId ON DanhGia(GiayId);
CREATE INDEX IX_DanhGia_KhachHangId ON DanhGia(KhachHangId);
CREATE INDEX IX_ThanhToan_HoaDonId ON ThanhToan(HoaDonId);
CREATE INDEX IX_PhieuTraHang_HoaDonId ON PhieuTraHang(HoaDonId);
CREATE INDEX IX_Giay_ThuongHieuId ON Giay(ThuongHieuId);
CREATE INDEX IX_Giay_LoaiGiayId ON Giay(LoaiGiayId);
CREATE INDEX IX_Giay_ChatLieuId ON Giay(ChatLieuId);
GO

